services:

  # -----------------------
  # PostgreSQL
  # -----------------------
  postgres:
    image: postgres:15
    container_name: order_analytics_postgres
    environment:
      POSTGRES_DB: order_analytics
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pwd
    ports:
      - "5433:5432"
    volumes:
      - order_analytics_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # -----------------------
  # Zookeeper
  # -----------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: order_analytics_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # -----------------------
  # Kafka Broker
  # -----------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: order_analytics_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Proper dual listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT

      # External (host) + internal (Docker)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://order_analytics_kafka:29092

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092

      # Critical for Spark
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # -----------------------
  # Spark
  # -----------------------
  spark:
    image: apache/spark:3.5.0
    container_name: order_analytics_spark
    command: ["/bin/bash", "-c", "sleep infinity"]
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres

volumes:
  order_analytics_pgdata: